### ISSUE TITLE
프로그램에서 출력 언어를 어떻게 할까요?(한국어 or 영어?)

### ISSUE THREAD

**Issue by popobaboya** [popobaboya/CRUD_mini_project#4]
아린 학우님은 평소에 한국어랑 영어 둘 중에 어떤 걸로 사용하셨나요?
ex) printf("상품 이름은?"); or printf("Enter product's name");

제가 리눅스에서는 영어를 사용해서 혹시 언어가 다를까봐 이슈를 개설했습니다..!
아린 학우님이 원래 사용하시던 쪽으로 맞추겠습니당

**Comment by ajjang** [comment]
전 영어로 써도 상관없습니다 너무늦게확인했네요ㅜㅜ

**Comment by popobaboya** [comment]
아니예요~! 그럼 영어로 하겠습니다
